### ISSUE TITLE
using as glyph not working

### ISSUE THREAD

**Issue by ghost** [yusbel80/extjs-package-fontawesome#1]
Hi,

thanks for this package.
I am trying to use it in a 6.6 classic app and I can successfully use it when I use the css classes in 'iconCls' config. However I am unable to use it as a glyph for a button like:

xf2f5@Font Awesome 5 Free

Have you used the glyphs sucessfully?

**Comment by yusbel80** [comment]
Thanks for the reply, It is working for me, please remember that new icons must be manually added to the scss class. 
<img width="291" alt="Screen Shot 2019-03-26 at 8 08 18 AM" src="https://user-images.githubusercontent.com/8496256/54995962-7487e180-4f9e-11e9-99f0-59ab7eb24e23.png">
<img width="104" alt="Screen Shot 2019-03-26 at 8 08 29 AM" src="https://user-images.githubusercontent.com/8496256/54995973-7c478600-4f9e-11e9-8813-c9b7032a4cba.png">

**Comment by ghost** [comment]
Can you please tell me in what scss file the icons must be added? Thanks

**Comment by yusbel80** [comment]
After you've updated the latest fonts on the resource folder, you must also update the "_variables.scss" on path /sass/etc/_variables.scss to reflect the name changes

**Comment by ghost** [comment]
This icon is also working for me, but can you try for example: $fa-var-sign-out-alt: "\f2f5"; as a glyph? It only shows a rectangle for me.

I tried with xf2f5@Font Awesome 5 Free and xf2f5@FontAwesome

The difference to the one you made the example is that it is new in the 5.x version of font-awesome.

**Comment by yusbel80** [comment]
If it is showing a square is because it's either nor on the variables scss or not in the resource. Font awesome regularly updates their icons, so must you do the same in the package.

**Comment by ghost** [comment]
I downloaded the latest version of font-awesome today and updated the resources. 
The icon is available since 5.0: https://fontawesome.com/icons/sign-out-alt?style=solid

And it is in the _variables.scss file
![sign-out-alt](https://user-images.githubusercontent.com/33218011/55003834-66a38200-4fd9-11e9-8f9c-58ba1c531a03.png)


If you maybe have any idea where I should start looking how to solve this? thank you
